---

name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Check licenses
        run: |
          dart pub global activate very_good_cli
          dart pub global run very_good_cli:very_good packages check licenses \
            --dependency-type='direct-main,transitive' \
            --allowed='MIT,BSD-3-Clause,BSD-2-Clause,Apache-2.0,Zlib'

      - name: Analyze code (lint)
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Analyze code (format)
        run: dart format --set-exit-if-changed .

      - name: Run test
        run: flutter test --coverage

      - name: Check test coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: '${{ github.workspace }}/coverage/lcov.info'
          exclude: '**/*_observer.dart'
          min_coverage: 60

      - name: Build appbundle
        run: flutter build appbundle --release

      - name: Build apk
        run: flutter build apk --release

      - name: Build apk per ABI
        run: flutter build apk --split-per-abi

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          owner: ${{ github.repository_owner }}
          body: 'See [CHANGELOG](https://github.com/tmaegel/ntodotxt/blob/main/CHANGELOG.md)'
          artifacts: >
            build/app/outputs/bundle/release/app-release.aab,
            build/app/outputs/flutter-apk/app-release.apk,
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk,
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk,
            build/app/outputs/flutter-apk/app-x86_64-release.apk
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
